# Maths Challenge Quiz - Testing Makefile
# Copyright 2019 - Ethan Marshall
#
# To build the testing script, use the options `build`, `run` or `test` at the command line

none:
	@echo "Please supply either build, run or test at the command line"
	@echo "At least one of these options is required"

build:

run:

test:

.PHONY none